### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by wolterbwambale** [M-AminAlizadeh/Microverse-capstone-2#22]
Good job so far!
Highlights!

    Good code organization and working app ✔️
    Descriptive README ✔️
   Gitflow 💯 
   

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!
Status: Required Changes ♻️⛔️
you can start adding javascript to make the website or your application so interactive.

cheers and happy coding.

**Comment by gergitokusse** [comment]
#### 🙏 Thank you very much my morning session teammates @wolterbwambale and Phelelani for you give us important feedback.

### Cheers 👊👊👊 and Happy coding👍👍👍👍 !
