### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by techmoves** [M-AminAlizadeh/Microverse-capstone-2#31]
Great work , your are doing well 👍 
.
Great work ,

![IApproveSimonCowellGIF](https://github.com/M-AminAlizadeh/Microverse-capstone-2/assets/110924992/2f7138c3-ca5a-4276-bc99-3d8393a55ccb)
 
- [x] you use es6✔️
- [x] your code is clean✔️
- [x] keep it up

Cheers and happy coding

**Comment by M-AminAlizadeh** [comment]
Thank you @techmoves
